version: "3.9"

services:
  backend:
    build: ./backend
    container_name: quiz-backend
    ports:
      - "8080:8080"
    volumes:
      - quiz_data:/app/data
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlite:/app/quiz.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  frontend:
    build: ./frontend
    container_name: quiz-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE=http://backend:8080
    depends_on:
      backend:
        condition: service_healthy
    restart: always

volumes:
  quiz_data: